apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: ping
spec:
  metric:
    enabled: true
    http:
      increasedCardinality: false
  # tracing:
  #   samplingRate: "1"
  #   zipkin:
  #     endpointAddress: "http://zipkin:9411/api/v2/spans"
  mtls:
    allowedClockSkew: 15m
    enabled: true
    workloadCertTTL: 24h
  features:
    - name: Resiliency
      enabled: true
  # api:
    # allowed:
    # - name: state
    #   version: v1
    #   protocol: http
    # - name: publish
    #   version: v1
    #   protocol: http
    # TODO enable service-to-service invocation and configure ACLs 